- name: Provision EC2
  connection: local
  gather_facts: false
  hosts: localhost
  vars_files:
    - variables/default.yml

  tasks:
  - name: Launch instance 
    ec2:
      assign_public_ip: true
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      count: "{{ count }}"
      group: "{{ security_group }}"
      image: "{{ image }}" 
      instance_type: "{{ instance_type }}"
      key_name: "{{ key_name }}"
      region: "{{ region }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      wait: true
    register: ec2
  - name: Log information
    debug: var=ec2
