- name: Setup EC2
  become: true
  gather_facts: false
  hosts: namenode

  pre_tasks:
  - name: Install python
    raw: sudo apt-get -y install python
      
  tasks:
  - name: Install openjdk-9-jdk-headless
    apt: pkg=openjdk-9-jdk-headless state=latest
